In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd
import numpy as np

In [2]:
from bs4 import BeautifulSoup
import requests

#from selenium import webdriver
#from selenium.webdriver.chrome.service import Service
#from webdriver_manager.chrome import ChromeDriverManager
#from selenium.webdriver.common.by import By

In [3]:
data = pd.read_csv("D:/IndicWiki/120001-end.csv")
#driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
#driver.get('https://business.mapsofindia.com/india-company/')
#driver.maximize_window()

In [4]:
d = data[data.ownership!='Limited Liability Partnership']

In [5]:
d

,CIN,Name,url,roc,status,ownership
0,U31909HP2021PTC008617,BAALAK INDUSTRIES PRIVATE LIMITED,https://www.zaubacorp.com/company/BAALAK-INDUS...,HimachalPradesh,Active,Private Limited Company
1,U85191UP2016PTC076583,BAALARK MEDITRADE SERVICES PRIVATE LIMITED,https://www.zaubacorp.com/company/BAALARK-MEDI...,Kanpur,Active,Private Limited Company
2,U85320RJ2017NPL058583,BAALASRI MICROFINANCE INDIA ASSOCIATION,https://www.zaubacorp.com/company/BAALASRI-MIC...,Jaipur,Active,Not-for-Profit License Company
4,U74999KL2019PTC056164,BAALSWASTIK SYSTEMS INDIA PRIVATE LIMITED,https://www.zaubacorp.com/company/BAALSWASTIK-...,Ernakulam,Active,Private Limited Company
5,U85191KA2019PTC122476,BAALYAM HEALTHCARE PRIVATE LIMITED,https://www.zaubacorp.com/company/BAALYAM-HEAL...,Bangalore,Active,Private Limited Company
...,...,...,...,...,...,...
58574,U29309RJ2010PTC033499,ECO SOL ENERGY PRIVATE LIMITED,https://www.zaubacorp.com/company/ECO-SOL-ENER...,Jaipur,Active,Private Limited Company
58575,U40106MH2021PTC370447,ECO SOLAR SOLUTIONS INDIA PRIVATE LIMITED,https://www.zaubacorp.com/company/ECO-SOLAR-SO...,Mumbai,Active,Private Limited Company
58576,U27100TG2008PLC058999,ECO STEEL INDIA LIMITED,https://www.zaubacorp.com/company/ECO-STEEL-IN...,Hyderabad,Active,Public Limited Company
58577,U14200KL2020PTC065291,ECO STONEPRODUCTS PRIVATE LIMITED,https://www.zaubacorp.com/company/ECO-STONEPRO...,Ernakulam,Active,Private Limited Company
58578,U74999WB2012PTC176813,ECO STREAM FASHION PRIVATE LIMITED,https://www.zaubacorp.com/company/ECO-STREAM-F...,Kolkata,Active,Private Limited Company

In [19]:
cols = ['Company Category','Company Sub Category','Class of Company','Date of Incorporation','Age of Company',
       'Activity','Authorised Capital','Paid up capital','Director Name','Address']
df = pd.DataFrame(columns=cols)
c=0

In [37]:
for url in d.url[40000:]:
    c+=1
    try:
        page = requests.get(url)
        soup = BeautifulSoup(page.text, 'html5lib')
        table1 = soup.findAll('table')
        table3 = soup.find('div', class_='col-12')
        l = [table1[0].find_all('p')[i].text for i in range(1,len(table1[0].find_all('p')),2)][5:-1]
        l.append(table1[3].find_all('p')[1].text)
        l.append(table1[3].find_all('p')[3].text)
        l.append(table1[7].find_all('p')[1].text)
        l.append(table3.find_all('p')[3].text)
        df.loc[len(df)] = l
    except:
        df.loc[len(df)] = [np.nan]*df.shape[1]
    if c%100==0:
        print(c)
df

40100
40200
40300
40400
40500
40600
40700
40800
40900
41000
41100
41200
41300
41400
41500
41600
41700
41800
41900
42000
42100
42200
42300
42400
42500
42600
42700
42800
42900
43000
43100
43200
43300
43400
43500
43600
43700
43800
43900
44000
44100
44200
44300
44400
44500
44600
44700
44800
44900
45000
45100
45200
45300
45400
45500
45600
45700
45800
45900
46000
46100
46200
46300
46400
46500
46600
46700
46800
46900
47000
47100
47200
47300
47400
47500
47600
47700
47800
47900
48000
48100
48200
48300
48400
48500
48600
48700
48800
48900
49000
49100
49200
49300
49400
49500
49600
49700
49800
49900
50000
50100
50200
50300
50400
50500
50600
50700

,Company Category,Company Sub Category,Class of Company,Date of Incorporation,Age of Company,Activity,Authorised Capital,Paid up capital,Director Name,Address
0,Company limited by Shares,Non-govt company,Private,14 June 2021,"0 years, 9 month, 13 days",Manufacture of other electrical equip ment n.e.c.,"₹100,000","₹100,000",Shyam Lal,237 Village-Chakrog post office-Drubbai Teh Ro...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Company limited by Shares,Non-govt company,Private,18 July 2017,"4 years, 8 month, 9 days",Social work activities,"₹1,000,000","₹1,000,000",SULTAN SINGH RANWA,"S/O HEMA RAM RANWA,KHUD DATARAMGARH,LOSAL SIKA..."
3,Company limited by Shares,Non-govt company,Private,02 January 2019,"3 years, 2 month, 25 days",Business activities n.e.c.,"₹1,000,000","₹1,000,000",RAJESH MOHAN,"7/237-F, THANNICKAL BUILDING THADIYOOR.P.O, TH..."
4,Company limited by Shares,Non-govt company,Private,18 March 2019,"3 years, 0 month, 9 days",Human health activities,"₹100,000","₹100,000",AMMINI VASUDEVAN,"No.25/1-4, 1st Floor, 9th Cross, 19th A Main,M..."
...,...,...,...,...,...,...,...,...,...,...
50706,Company limited by Shares,Non-govt company,Private,08 December 2010,"11 years, 3 month, 19 days","Manufacture of domestic appliances, n.e.c.","₹100,000","₹100,000",BRAJBHUSHAN NAUSALIYA,"15/6, VIDHYA MARG, SAGAR ENCLAVE, FATEHPURA UD..."
50707,Company limited by Shares,Non-govt company,Private,27 October 2021,"0 years, 5 month, 0 days","Production , collection and distribution of el...","₹500,000","₹100,000",SHILPA SUDHIR WAGHMARE,"FLAT C-402, HITESH APARTMENTS CHSL NETAJI PALK..."
50708,Company limited by Shares,Non-govt company,Public,05 May 2008,"13 years, 10 month, 22 days",Manufacture of Basic Iron & Steel,"₹2,500,000","₹500,000",NIMISH GADODIA,"8-2-614/A/B/3/1, Flat-401 Burri Residency, Roa..."
50709,Company limited by Shares,Non-govt company,Private,24 October 2020,"1 years, 5 month, 3 days","Mining and quarrying , n.e.c.","₹1,000,000","₹100,000",ABDULLA SHAMEER NADUKANDATHIL,"H.NO: 16/48,OZHUPARAKKAL HOUSE KODIYATHUR PO,M..."
50710,Company limited by Shares,Non-govt company,Private,23 March 2012,"10 years, 0 month, 4 days",Business activities n.e.c.,"₹100,000","₹100,000",DEEPAK TANDON,24/3 Moulana Abul Kalam Azad Sarani Kolkata Ko...

In [38]:
df.to_csv("D:\IndicWiki\Final_companies_result.csv")